module.exports = {
  plugins: ['angular'],
  rules: {
    'angular/component-name': 'error',
    'angular/constant-name': 'error',
    'angular/controller-as-route': 'error',
    'angular/controller-as-vm': 'error',
    'angular/controller-as': 'error',
    'angular/controller-name': 'error',
    'angular/directive-name': 'error',
    'angular/directive-restrict': 'error',
    'angular/document-service': 'error',
    'angular/factory-name': 'error',
    'angular/file-name': 'error',
    'angular/filter-name': 'error',
    'angular/function-type': 'error',
    'angular/interval-service': 'error',
    'angular/module-getter': 'error',
    'angular/module-name': 'error',
    'angular/module-setter': 'error',
    'angular/no-run-logic': 'error',
    'angular/no-service-method': 'error',
    'angular/provider-name': 'error',
    'angular/service-name': 'error',
    'angular/timeout-service': 'error',
    'angular/value-name': 'error',
    'angular/window-service': 'error',
  },
};
